indexing
	description:
		"[
			This class contains test cases. 
                     TODO: Put proper description of class here.
			Visit http://dev.eiffel.com/CddBranch for more information.
		]"
	author: "EiffelStudio CDD Tool"
	date: "$Date$"
	revision: "$Revision$"

class
	$classname

inherit

	CDD_TEST_CASE

feature -- Tests

	test_1 is
			-- TODO: Put header comment here.
		do
			-- TODO: Below is a sample test, replace with your own.
                     
                     assert ("one plus one is two", 1 + 1 = 2)
		end

end
