indexing
	description:
		"[
			This manual test class has been created by CDD.
			Visit http://dev.eiffel.com/CddBranch for more information.
		]"
	author: "EiffelStudio CDD Tool"
	date: "$Date$"
	revision: "$Revision$"

class
	$classname

inherit

	CDD_TEST_CASE

feature -- Tests

	test_1 is
			-- Test something.
		do
			-- TODO: Implement your unit test
			assert ("implemented", False)
		end

end
