CREATE TABLE  `semantic_search`.`Queryables` (
  `qry_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `qry_kind` tinyint(3) unsigned NOT NULL,
  `class` varchar(128) DEFAULT NULL,
  `feature` varchar(128) DEFAULT NULL,
  `library` varchar(128) DEFAULT NULL,
  `transition_status` tinyint(3) unsigned DEFAULT NULL,
  `hit_breakpoints` text,
  `timestamp` varchar(128) DEFAULT NULL,
  `uuid` char(36) NOT NULL,
  `is_creation` tinyint(3) unsigned DEFAULT NULL,
  `is_query` tinyint(3) unsigned DEFAULT NULL,
  `argument_count` tinyint(3) unsigned DEFAULT NULL,
  `pre_serialization` longtext,
  `pre_serialization_info` text,
  `post_serialization` longtext,
  `post_serialization_info` text,
  `exception_recipient` varchar(128) DEFAULT NULL,
  `exception_class` varchar(128) DEFAULT NULL,
  `exception_breakpoint` int(11) DEFAULT NULL,
  `exception_code` int(11) DEFAULT NULL,
  `exception_meaning` varchar(256) DEFAULT NULL,
  `exception_tag` varchar(256) DEFAULT NULL,
  `exception_trace` text,
  `fault_signature` varchar(256) DEFAULT NULL,
  PRIMARY KEY (`qry_id`) USING BTREE,
  KEY `class_index` (`class`),
  KEY `feature_index` (`feature`),
  KEY `library_index` (`library`),
  KEY `transition_status_index` (`transition_status`),
  KEY `timestamp_index` (`timestamp`),
  KEY `uuid_index` (`uuid`),
  KEY `is_creation_index` (`is_creation`),
  KEY `is_query_index` (`is_query`),
  KEY `argument_count_index` (`argument_count`),
  KEY `qry_kind_index` (`qry_kind`) USING BTREE,
  KEY `exception_recipient_index` (`exception_recipient`),
  KEY `exception_class_index` (`exception_class`),
  KEY `exception_code_index` (`exception_code`),
  KEY `exception_meaning_index` (`exception_meaning`),
  KEY `exception_tag_index` (`exception_tag`),
  KEY `fault_signature_index` (`fault_signature`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE  `semantic_search`.`Types` (
  `type_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `type_name` varchar(128) NOT NULL,
  PRIMARY KEY (`type_id`),
  KEY `type_name_index` (`type_name`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE  `semantic_search`.`Conformances` (
  `type_id` int(10) unsigned NOT NULL,
  `conf_type_id` int(10) unsigned NOT NULL,
  KEY `type_id_index` (`type_id`),
  KEY `conf_type_id_fk` (`conf_type_id`),
  CONSTRAINT `conf_type_id_fk` FOREIGN KEY (`conf_type_id`) REFERENCES `Types` (`type_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `type_id_fk` FOREIGN KEY (`type_id`) REFERENCES `Types` (`type_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE  `semantic_search`.`Properties` (
  `prop_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `text` varchar(256) NOT NULL,
  PRIMARY KEY (`prop_id`),
  KEY `text_index` (`text`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE  `semantic_search`.`PropertyBindings1` (
  `prop_id` int(10) unsigned NOT NULL,
  `qry_id` int(10) unsigned NOT NULL,
  `var1` int(10) unsigned NOT NULL,
  `type1` int(10) unsigned NOT NULL,
  `value` int(11) NOT NULL,
  `equal_value` int(11) NOT NULL,
  `boost` double unsigned NOT NULL,
  `value_type_kind` tinyint(3) unsigned NOT NULL,
  `prop_kind` tinyint(3) unsigned NOT NULL,
  `position` int(10) unsigned,
  KEY `sb1_qry_id_fk` (`qry_id`),
  KEY `sb1_type1_fk` (`type1`),
  KEY `sb1_index` (`prop_id`,`type1`,`value`,`equal_value`) USING BTREE,
  CONSTRAINT `sb1_prop_id_fk` FOREIGN KEY (`prop_id`) REFERENCES `Properties` (`prop_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `sb1_qry_id_fk` FOREIGN KEY (`qry_id`) REFERENCES `Queryables` (`qry_id`),
  CONSTRAINT `sb1_type1_fk` FOREIGN KEY (`type1`) REFERENCES `Types` (`type_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE  `semantic_search`.`PropertyBindings2` (
  `prop_id` int(10) unsigned NOT NULL,
  `qry_id` int(10) unsigned NOT NULL,
  `var1` int(10) unsigned NOT NULL,
  `type1` int(10) unsigned NOT NULL,
  `var2` int(10) unsigned NOT NULL,
  `type2` int(10) unsigned NOT NULL,
  `value` int(11) NOT NULL,
  `equal_value` int(11) NOT NULL,
  `boost` double unsigned NOT NULL,
  `prop_kind` tinyint(3) unsigned NOT NULL,
  `value_type_kind` tinyint(3) unsigned NOT NULL,
  KEY `sb2_index` (`prop_id`,`type1`,`type2`,`value`,`equal_value`) USING BTREE,
  KEY `sb2_qry_id_fk` (`qry_id`),
  KEY `sb2_type1_fk` (`type1`),
  KEY `sb2_type2_fk` (`type2`),
  CONSTRAINT `sb2_type1_fk` FOREIGN KEY (`type1`) REFERENCES `Types` (`type_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `sb2_type2_fk` FOREIGN KEY (`type2`) REFERENCES `Types` (`type_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `sb2_prop_id_fk` FOREIGN KEY (`prop_id`) REFERENCES `Properties` (`prop_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `sb2_qry_id_fk` FOREIGN KEY (`qry_id`) REFERENCES `Queryables` (`qry_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE  `semantic_search`.`PropertyBindings3` (
  `prop_id` int(10) unsigned NOT NULL,
  `qry_id` int(10) unsigned NOT NULL,
  `var1` int(10) unsigned NOT NULL,
  `type1` int(10) unsigned NOT NULL,
  `var2` int(10) unsigned NOT NULL,
  `type2` int(10) unsigned NOT NULL,
  `var3` int(10) unsigned NOT NULL,
  `type3` int(10) unsigned NOT NULL,
  `value` int(11) NOT NULL,
  `equal_value` int(11) NOT NULL,
  `boost` double unsigned NOT NULL,
  `prop_kind` tinyint(3) unsigned NOT NULL,
  `value_type_kind` tinyint(3) unsigned NOT NULL,
  KEY `sb3_index` (`prop_id`,`type1`,`type2`, `type3`, `value`,`equal_value`) USING BTREE,
  KEY `sb3_qry_id_fk` (`qry_id`),
  KEY `sb3_type1_fk` (`type1`),
  KEY `sb3_type2_fk` (`type2`),
  KEY `sb3_type3_fk` (`type3`),
  CONSTRAINT `sb3_type1_fk` FOREIGN KEY (`type1`) REFERENCES `Types` (`type_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `sb3_type2_fk` FOREIGN KEY (`type2`) REFERENCES `Types` (`type_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `sb3_type3_fk` FOREIGN KEY (`type3`) REFERENCES `Types` (`type_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `sb3_prop_id_fk` FOREIGN KEY (`prop_id`) REFERENCES `Properties` (`prop_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `sb3_qry_id_fk` FOREIGN KEY (`qry_id`) REFERENCES `Queryables` (`qry_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE  `semantic_search`.`PropertyBindings4` (
  `prop_id` int(10) unsigned NOT NULL,
  `qry_id` int(10) unsigned NOT NULL,
  `var1` int(10) unsigned NOT NULL,
  `type1` int(10) unsigned NOT NULL,
  `var2` int(10) unsigned NOT NULL,
  `type2` int(10) unsigned NOT NULL,
  `var3` int(10) unsigned NOT NULL,
  `type3` int(10) unsigned NOT NULL,
  `var4` int(10) unsigned NOT NULL,
  `type4` int(10) unsigned NOT NULL,
  `value` int(11) NOT NULL,
  `equal_value` int(11) NOT NULL,
  `boost` double unsigned NOT NULL,
  `prop_kind` tinyint(3) unsigned NOT NULL,
  `value_type_kind` tinyint(3) unsigned NOT NULL,
  KEY `sb4_index` (`prop_id`,`type1`,`type2`, `type3`, `type4`, `value`,`equal_value`) USING BTREE,
  KEY `sb4_qry_id_fk` (`qry_id`),
  KEY `sb4_type1_fk` (`type1`),
  KEY `sb4_type2_fk` (`type2`),
  KEY `sb4_type3_fk` (`type3`),
  KEY `sb4_type4_fk` (`type4`),
  CONSTRAINT `sb4_type1_fk` FOREIGN KEY (`type1`) REFERENCES `Types` (`type_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `sb4_type2_fk` FOREIGN KEY (`type2`) REFERENCES `Types` (`type_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `sb4_type3_fk` FOREIGN KEY (`type3`) REFERENCES `Types` (`type_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `sb4_type4_fk` FOREIGN KEY (`type4`) REFERENCES `Types` (`type_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `sb4_prop_id_fk` FOREIGN KEY (`prop_id`) REFERENCES `Properties` (`prop_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `sb4_qry_id_fk` FOREIGN KEY (`qry_id`) REFERENCES `Queryables` (`qry_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE  `semantic_search`.`PropertyBindings5` (
  `prop_id` int(10) unsigned NOT NULL,
  `qry_id` int(10) unsigned NOT NULL,
  `var1` int(10) unsigned NOT NULL,
  `type1` int(10) unsigned NOT NULL,
  `var2` int(10) unsigned NOT NULL,
  `type2` int(10) unsigned NOT NULL,
  `var3` int(10) unsigned NOT NULL,
  `type3` int(10) unsigned NOT NULL,
  `var4` int(10) unsigned NOT NULL,
  `type4` int(10) unsigned NOT NULL,
  `var5` int(10) unsigned NOT NULL,
  `type5` int(10) unsigned NOT NULL,
  `value` int(11) NOT NULL,
  `equal_value` int(11) NOT NULL,
  `boost` double unsigned NOT NULL,
  `prop_kind` tinyint(3) unsigned NOT NULL,
  `value_type_kind` tinyint(3) unsigned NOT NULL,
  KEY `sb5_index` (`prop_id`,`type1`,`type2`, `type3`, `type4`, `type5`, `value`,`equal_value`) USING BTREE,
  KEY `sb5_qry_id_fk` (`qry_id`),
  KEY `sb5_type1_fk` (`type1`),
  KEY `sb5_type2_fk` (`type2`),
  KEY `sb5_type3_fk` (`type3`),
  KEY `sb5_type4_fk` (`type4`),
  KEY `sb5_type5_fk` (`type5`),
  CONSTRAINT `sb5_type1_fk` FOREIGN KEY (`type1`) REFERENCES `Types` (`type_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `sb5_type2_fk` FOREIGN KEY (`type2`) REFERENCES `Types` (`type_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `sb5_type3_fk` FOREIGN KEY (`type3`) REFERENCES `Types` (`type_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `sb5_type4_fk` FOREIGN KEY (`type4`) REFERENCES `Types` (`type_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `sb5_type5_fk` FOREIGN KEY (`type5`) REFERENCES `Types` (`type_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `sb5_prop_id_fk` FOREIGN KEY (`prop_id`) REFERENCES `Properties` (`prop_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `sb5_qry_id_fk` FOREIGN KEY (`qry_id`) REFERENCES `Queryables` (`qry_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


CREATE TABLE  `semantic_search`.`PropertyBindings6` (
  `prop_id` int(10) unsigned NOT NULL,
  `qry_id` int(10) unsigned NOT NULL,
  `var1` int(10) unsigned NOT NULL,
  `type1` int(10) unsigned NOT NULL,
  `var2` int(10) unsigned NOT NULL,
  `type2` int(10) unsigned NOT NULL,
  `var3` int(10) unsigned NOT NULL,
  `type3` int(10) unsigned NOT NULL,
  `var4` int(10) unsigned NOT NULL,
  `type4` int(10) unsigned NOT NULL,
  `var5` int(10) unsigned NOT NULL,
  `type5` int(10) unsigned NOT NULL,
  `var6` int(10) unsigned NOT NULL,
  `type6` int(10) unsigned NOT NULL,
  `value` int(11) NOT NULL,
  `equal_value` int(11) NOT NULL,
  `boost` double unsigned NOT NULL,
  `prop_kind` tinyint(3) unsigned NOT NULL,
  `value_type_kind` tinyint(3) unsigned NOT NULL,
  KEY `sb6_index` (`prop_id`,`type1`,`type2`, `type3`, `type4`, `type5`, `type6`, `value`,`equal_value`) USING BTREE,
  KEY `sb6_qry_id_fk` (`qry_id`),
  KEY `sb6_type1_fk` (`type1`),
  KEY `sb6_type2_fk` (`type2`),
  KEY `sb6_type3_fk` (`type3`),
  KEY `sb6_type4_fk` (`type4`),
  KEY `sb6_type5_fk` (`type5`),
  KEY `sb6_type6_fk` (`type6`),
  CONSTRAINT `sb6_type1_fk` FOREIGN KEY (`type1`) REFERENCES `Types` (`type_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `sb6_type2_fk` FOREIGN KEY (`type2`) REFERENCES `Types` (`type_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `sb6_type3_fk` FOREIGN KEY (`type3`) REFERENCES `Types` (`type_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `sb6_type4_fk` FOREIGN KEY (`type4`) REFERENCES `Types` (`type_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `sb6_type5_fk` FOREIGN KEY (`type5`) REFERENCES `Types` (`type_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `sb6_type6_fk` FOREIGN KEY (`type6`) REFERENCES `Types` (`type_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `sb6_prop_id_fk` FOREIGN KEY (`prop_id`) REFERENCES `Properties` (`prop_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `sb6_qry_id_fk` FOREIGN KEY (`qry_id`) REFERENCES `Queryables` (`qry_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE  `semantic_search`.`PropertyBindings7` (
  `prop_id` int(10) unsigned NOT NULL,
  `qry_id` int(10) unsigned NOT NULL,
  `var1` int(10) unsigned NOT NULL,
  `type1` int(10) unsigned NOT NULL,
  `var2` int(10) unsigned NOT NULL,
  `type2` int(10) unsigned NOT NULL,
  `var3` int(10) unsigned NOT NULL,
  `type3` int(10) unsigned NOT NULL,
  `var4` int(10) unsigned NOT NULL,
  `type4` int(10) unsigned NOT NULL,
  `var5` int(10) unsigned NOT NULL,
  `type5` int(10) unsigned NOT NULL,
  `var6` int(10) unsigned NOT NULL,
  `type6` int(10) unsigned NOT NULL,
  `var7` int(10) unsigned NOT NULL,
  `type7` int(10) unsigned NOT NULL,
  `value` int(11) NOT NULL,
  `equal_value` int(11) NOT NULL,
  `boost` double unsigned NOT NULL,
  `prop_kind` tinyint(3) unsigned NOT NULL,
  `value_type_kind` tinyint(3) unsigned NOT NULL,
  KEY `sb7_index` (`prop_id`,`type1`,`type2`, `type3`, `type4`, `type5`, `type6`, `type7`, `value`,`equal_value`) USING BTREE,
  KEY `sb7_qry_id_fk` (`qry_id`),
  KEY `sb7_type1_fk` (`type1`),
  KEY `sb7_type2_fk` (`type2`),
  KEY `sb7_type3_fk` (`type3`),
  KEY `sb7_type4_fk` (`type4`),
  KEY `sb7_type5_fk` (`type5`),
  KEY `sb7_type6_fk` (`type6`),
  KEY `sb7_type7_fk` (`type7`),
  CONSTRAINT `sb7_type1_fk` FOREIGN KEY (`type1`) REFERENCES `Types` (`type_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `sb7_type2_fk` FOREIGN KEY (`type2`) REFERENCES `Types` (`type_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `sb7_type3_fk` FOREIGN KEY (`type3`) REFERENCES `Types` (`type_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `sb7_type4_fk` FOREIGN KEY (`type4`) REFERENCES `Types` (`type_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `sb7_type5_fk` FOREIGN KEY (`type5`) REFERENCES `Types` (`type_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `sb7_type6_fk` FOREIGN KEY (`type6`) REFERENCES `Types` (`type_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `sb7_type7_fk` FOREIGN KEY (`type7`) REFERENCES `Types` (`type_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `sb7_prop_id_fk` FOREIGN KEY (`prop_id`) REFERENCES `Properties` (`prop_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `sb7_qry_id_fk` FOREIGN KEY (`qry_id`) REFERENCES `Queryables` (`qry_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE  `semantic_search`.`PropertyBindings8` (
  `prop_id` int(10) unsigned NOT NULL,
  `qry_id` int(10) unsigned NOT NULL,
  `var1` int(10) unsigned NOT NULL,
  `type1` int(10) unsigned NOT NULL,
  `var2` int(10) unsigned NOT NULL,
  `type2` int(10) unsigned NOT NULL,
  `var3` int(10) unsigned NOT NULL,
  `type3` int(10) unsigned NOT NULL,
  `var4` int(10) unsigned NOT NULL,
  `type4` int(10) unsigned NOT NULL,
  `var5` int(10) unsigned NOT NULL,
  `type5` int(10) unsigned NOT NULL,
  `var6` int(10) unsigned NOT NULL,
  `type6` int(10) unsigned NOT NULL,
  `var7` int(10) unsigned NOT NULL,
  `type7` int(10) unsigned NOT NULL,
  `var8` int(10) unsigned NOT NULL,
  `type8` int(10) unsigned NOT NULL,
  `value` int(11) NOT NULL,
  `equal_value` int(11) NOT NULL,
  `boost` double unsigned NOT NULL,
  `prop_kind` tinyint(3) unsigned NOT NULL,
  `value_type_kind` tinyint(3) unsigned NOT NULL,
  KEY `sb8_index` (`prop_id`,`type1`,`type2`, `type3`, `type4`, `type5`, `type6`, `type7`, `type8`, `value`,`equal_value`) USING BTREE,
  KEY `sb8_qry_id_fk` (`qry_id`),
  KEY `sb8_type1_fk` (`type1`),
  KEY `sb8_type2_fk` (`type2`),
  KEY `sb8_type3_fk` (`type3`),
  KEY `sb8_type4_fk` (`type4`),
  KEY `sb8_type5_fk` (`type5`),
  KEY `sb8_type6_fk` (`type6`),
  KEY `sb8_type7_fk` (`type7`),
  KEY `sb8_type8_fk` (`type8`),
  CONSTRAINT `sb8_type1_fk` FOREIGN KEY (`type1`) REFERENCES `Types` (`type_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `sb8_type2_fk` FOREIGN KEY (`type2`) REFERENCES `Types` (`type_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `sb8_type3_fk` FOREIGN KEY (`type3`) REFERENCES `Types` (`type_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `sb8_type4_fk` FOREIGN KEY (`type4`) REFERENCES `Types` (`type_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `sb8_type5_fk` FOREIGN KEY (`type5`) REFERENCES `Types` (`type_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `sb8_type6_fk` FOREIGN KEY (`type6`) REFERENCES `Types` (`type_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `sb8_type7_fk` FOREIGN KEY (`type7`) REFERENCES `Types` (`type_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `sb8_type8_fk` FOREIGN KEY (`type8`) REFERENCES `Types` (`type_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `sb8_prop_id_fk` FOREIGN KEY (`prop_id`) REFERENCES `Properties` (`prop_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `sb8_qry_id_fk` FOREIGN KEY (`qry_id`) REFERENCES `Queryables` (`qry_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE  `semantic_search`.`PropertyBindings9` (
  `prop_id` int(10) unsigned NOT NULL,
  `qry_id` int(10) unsigned NOT NULL,
  `var1` int(10) unsigned NOT NULL,
  `type1` int(10) unsigned NOT NULL,
  `var2` int(10) unsigned NOT NULL,
  `type2` int(10) unsigned NOT NULL,
  `var3` int(10) unsigned NOT NULL,
  `type3` int(10) unsigned NOT NULL,
  `var4` int(10) unsigned NOT NULL,
  `type4` int(10) unsigned NOT NULL,
  `var5` int(10) unsigned NOT NULL,
  `type5` int(10) unsigned NOT NULL,
  `var6` int(10) unsigned NOT NULL,
  `type6` int(10) unsigned NOT NULL,
  `var7` int(10) unsigned NOT NULL,
  `type7` int(10) unsigned NOT NULL,
  `var8` int(10) unsigned NOT NULL,
  `type8` int(10) unsigned NOT NULL,
  `var9` int(10) unsigned NOT NULL,
  `type9` int(10) unsigned NOT NULL,
  `value` int(11) NOT NULL,
  `equal_value` int(11) NOT NULL,
  `boost` double unsigned NOT NULL,
  `prop_kind` tinyint(3) unsigned NOT NULL,
  `value_type_kind` tinyint(3) unsigned NOT NULL,
  KEY `sb9_index` (`prop_id`,`type1`,`type2`, `type3`, `type4`, `type5`, `type6`, `type7`, `type8`, `type9`, `value`,`equal_value`) USING BTREE,
  KEY `sb9_qry_id_fk` (`qry_id`),
  KEY `sb9_type1_fk` (`type1`),
  KEY `sb9_type2_fk` (`type2`),
  KEY `sb9_type3_fk` (`type3`),
  KEY `sb9_type4_fk` (`type4`),
  KEY `sb9_type5_fk` (`type5`),
  KEY `sb9_type6_fk` (`type6`),
  KEY `sb9_type7_fk` (`type7`),
  KEY `sb9_type8_fk` (`type8`),
  KEY `sb9_type9_fk` (`type9`),
  CONSTRAINT `sb9_type1_fk` FOREIGN KEY (`type1`) REFERENCES `Types` (`type_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `sb9_type2_fk` FOREIGN KEY (`type2`) REFERENCES `Types` (`type_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `sb9_type3_fk` FOREIGN KEY (`type3`) REFERENCES `Types` (`type_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `sb9_type4_fk` FOREIGN KEY (`type4`) REFERENCES `Types` (`type_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `sb9_type5_fk` FOREIGN KEY (`type5`) REFERENCES `Types` (`type_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `sb9_type6_fk` FOREIGN KEY (`type6`) REFERENCES `Types` (`type_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `sb9_type7_fk` FOREIGN KEY (`type7`) REFERENCES `Types` (`type_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `sb9_type8_fk` FOREIGN KEY (`type8`) REFERENCES `Types` (`type_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `sb9_type9_fk` FOREIGN KEY (`type9`) REFERENCES `Types` (`type_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `sb9_prop_id_fk` FOREIGN KEY (`prop_id`) REFERENCES `Properties` (`prop_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `sb9_qry_id_fk` FOREIGN KEY (`qry_id`) REFERENCES `Queryables` (`qry_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


