note
	description: "Summary description for {AFX_BOOLEAN_MODEL_STATE_TRANSITION_SUMMARY_MANAGER_POSTCONDITION_GUIDED}."
	author: ""
	date: "$Date$"
	revision: "$Revision$"

deferred class
	AFX_BOOLEAN_MODEL_STATE_TRANSITION_SUMMARY_MANAGER_POSTCONDITION_GUIDED

inherit
	AFX_BOOLEAN_MODEL_STATE_TRANSITION_SUMMARY_MANAGER_I

--	DS_HASH_TABLE [ DS_HASH_TABLE [ TUPLE [

end
