note
	description: "Summary description for {RM_ENVIRONMENT}."
	author: ""
	date: "$Date$"
	revision: "$Revision$"

deferred class
	RM_ENVIRONMENT

feature
	model_file_path: STRING
			-- the location of the model file generated by rapidminer
		deferred
		end

	performance_file_path: STRING
			-- the location of the performance file generated by rapidminer if validation is active
		deferred
		end

	rapid_miner_xml_file_path: STRING
			-- the location of the xml file needed to run rapidminer. This file tells rapidminer what to do.
		deferred
		end

	rapid_miner_working_directory:STRING
			-- where will rapidminer be executed. nothing is created here.
		deferred
		end

end

