# Makefile for my semester thesis
# Complete Contracts for EiffelBase
# Summer term 2007
# Marco Zietzling
#

all:
	rubber -d Report.tex
	evince Report.pdf &

clean:
#	-rm *~
	-rubber --clean Report.tex
