EC=${EIFFEL_SRC}/Eiffel/Ace/EIFGENs/batch/W_code/ecb

EC_STABLE=ec

EC_OPTS=-config senate_bus.ecf -target senate_bus -c_compile -stop -verbose

all:
	${EC} ${EC_OPTS}

regular:
	${EC_STABLE} ${EC_OPTS}
