#!/bin/sh

if [ "$1" == "local" ]; then
	echo $1
	export REMOTE=lisbon
	cp -f make_linuxppc ~/
	# Launch platform specific scripts
	rsh $REMOTE "cd local/TEST_DELIV ; mv -f ~/make_linuxppc ."
	rsh $REMOTE "cd local/TEST_DELIV ; ./make_linuxppc"

ftp -n << EOF 
verbose 
open lisbon.ise 
user manus manus 
binary
get local/TEST_DELIV/PorterPackage/Eiffel54_enterprise.tgz Eiffel54_ppc.tgz
get local/TEST_DELIV/PorterPackage/Eiffel54_enterprise.iso.gz Eiffel54_enterprise_ppc.iso.gz
get local/TEST_DELIV/PorterPackage/Eiffel54_university.iso.gz Eiffel54_university_ppc.iso.gz
get local/TEST_DELIV/PorterPackage/Eiffel54_free.iso.gz Eiffel54_free_ppc.iso.gz
close 
EOF

	echo LinuxPPC compilation done
else
	rm -rf PorterPackage
	tar xvf ~/PorterPackage_all.tar
	cd PorterPackage
	export ISE_PLATFORM=linuxppc
	compile_exes
	make_images
fi
