#!/bin/sh

if [ "$1" == "local" ]; then
	echo $1
	export REMOTE=mosis
	cp -f make_solaris ~/
	# Launch platform specific scripts
	rsh $REMOTE "cd local/TEST_DELIV ; mv -f ~/make_solaris ."
	rsh $REMOTE "cd local/TEST_DELIV ; bash ./make_solaris"

ftp -n << EOF 
verbose 
open mosis.ise 
user manus manus 
binary
get local/TEST_DELIV/PorterPackage/Eiffel54_enterprise.tgz Eiffel54_solaris.tgz
get local/TEST_DELIV/PorterPackage/Eiffel54_free.tgz Eiffel54_free_solaris.tgz
get local/TEST_DELIV/PorterPackage/Eiffel54_enterprise.iso.gz Eiffel54_enterprise_solaris.iso.gz
get local/TEST_DELIV/PorterPackage/Eiffel54_university.iso.gz Eiffel54_university_solaris.iso.gz
get local/TEST_DELIV/PorterPackage/Eiffel54_free.iso.gz Eiffel54_free_solaris.iso.gz
close 
EOF

	echo Solaris compilation done
else
	rm -rf PorterPackage
	tar xvf ~/PorterPackage_all.tar
	cd PorterPackage
	export ISE_PLATFORM=solaris-2.5+
	bash compile_exes
	bash make_images
fi
