#!/bin/sh

remtrace free_add_ons
cd $EIFFEL_SRC
co $DEFAULT_ORIGO_SVN/free_add_ons free_add_ons

remtrace gobo
cd $EIFFEL_SRC/library
gunzip -c $EIFFEL_SRC/free_add_ons/gobo/gobo_34_unix.tgz | tar -xf -

remtrace Compiling additional libraries
cd vision2/Clib
$ISE_EIFFEL/studio/spec/$ISE_PLATFORM/bin/finish_freezing -library >> $INSTALL_LOG
cd ../implementation/gtk/Clib
$ISE_EIFFEL/studio/spec/$ISE_PLATFORM/bin/finish_freezing -library >> $INSTALL_LOG

if [ "$1" = "gtk" ]; then
	# Copy GTK 1.2 implementation over gtk directory
	cd $EIFFEL_SRC/library/vision2/implementation/
	exprt $DEFAULT_ORIGO_SVN/Src/library/vision2_for_gtk12 gtk --force 
fi
cd $EIFFEL_SRC
