note
	description: "Keeps constants that are dependents on the user's OS."
	author: ""
	date: "$Date$"
	revision: "$Revision$"

deferred class
	RM_ENVIRONMENT

feature -- Access

	model_file_path: STRING
			-- The location of the model file generated by rapidminer
		deferred
		end

	performance_file_path: STRING
			-- The location of the performance file generated by rapidminer if validation is active
		deferred
		end

	rapid_miner_xml_file_path: STRING
			-- The location of the xml file needed to run rapidminer. This file tells rapidminer what to do.
		deferred
		end

	rapid_miner_arff_file_path: STRING
			-- The location of the arff file.
		deferred
		end

	rapid_miner_working_directory: STRING
			-- Where will rapidminer be executed. nothing is created here.
		deferred
		end

	rapid_miner_test_arff_path: STRING
			-- This is the absolute path to the test arff file. This file is just used for testing.
		deferred
		end

	tt: RM_TESTS

feature -- Status report

	should_remove_generated_files: BOOLEAN
			-- Should files generated for and by RapidMiner be removed
			-- after RapidMiner finishes?
			-- Default: False
		do
			Result := should_remove_generated_files_cell.item
		ensure
			good_result: Result = should_remove_generated_files_cell.item
		end

feature -- Setting

	set_should_remove_generated_files (b: BOOLEAN)
			-- Set `should_remove_generated_files' with `b'.
		do
			should_remove_generated_files_cell.put (b)
		ensure
			should_remove_generated_files_set: should_remove_generated_files = b
		end

feature{NONE} -- Implementation

	should_remove_generated_files_cell: CELL [BOOLEAN]
			-- Cell to store the value of `should_remove_generated_files'
		once
			create Result.put (False)
		end

end

