note
	description: "Class to run a customized RapidMiner process file"
	author: ""
	date: "$Date$"
	revision: "$Revision$"

class
	RM_PROCESS_RUNNER

create
	make

feature{NONE} -- Initialization

	make (a_process_file_path: STRING)
			-- Initialize Current.
		do
		end

feature -- Access

	inputs: HASH_TABLE [STRING, STRING]
			-- Input files
			-- Keys are input file indexes starting from "input0" to "input9".
			-- Values are absolute paths of those input files.
			-- If empty, then no input file is needed to execute the process file.

	outputs: HASH_TABLE [STRING, STRING]
			-- Output files
			-- Keys are output file indexes starting from "output0" to "output9".
			-- Values are absolute paths of those output files.
			-- If empty, then no output file will be generated by the execution of the
			-- process file.

	process_file_path: STRING
			-- Absolute path to the process file in RapidMiner format.

	memory: INTEGER
			-- Number of MB memory that is to be used by RapidMiner
			-- Default: 1024

	rapidminer_jar_path: STRING
			-- Absolute path to rapidminer.jar file which contains
			-- the main class of RapidMiner

feature -- Setting

end
