note
	description: "Summary description for {RM_DECISION_TREE_PARSER_INTERFACE}."
	author: ""
	date: "$Date$"
	revision: "$Revision$"

deferred class
	RM_DECISION_TREE_PARSER_INTERFACE

feature{RM_DECISION_TREE_PARSER_INTERFACE} -- Child access

	model_file_path: STRING
		-- Absolute path to the model file.

feature -- Access

	tree_root: RM_DECISION_TREE_NODE
		-- Will hold the root of the tree after the model file is parsed

feature -- Interface

	parse_model
			-- Parses the model file generated by rapidminer. The path to the file is saved in `model_file_path'.
		deferred
		end
end
